project:
  type: book
  output-dir: docs

book:
  title: "Statistical Learning in R for Social Sciences"
  author: "Alen Husnjak"
  date: last-modified
  chapters:
    - index.qmd
    - introduction_to_statistical_learning.qmd
    - part: 02_00_linear_regression.qmd
      chapters:
        - 02_01_quantitative_linear_regression.qmd
        - 02_02_qualitative_linear_regression.qmd
    - references.qmd

bibliography: references.bib
reference-location: section

format:
  html:
    toc: true
    number-sections: true
    code-tools: true
    css: styles.css
    theme:
      - cosmo
      - brand
